### ISSUE TITLE
User Story - Homepage

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#1]
EPIC: ** User Experience and Interface Design**

As a **user**, I can **be greeted by an inviting and informative homepage** so that **I can understand what the blog offers and decide where to navigate next**.

T-Shirt Size: **XL**

## **Acceptance Criteria**

- The homepage visually aligns with the blog's overall theme and branding.
- The homepage layout should be fully responsive for all screen sizes and devices.
- Latest articles are featured on the homepage.
- Call to action sign up is prominently displayed and engaging.
- The homepage loads quickly and performs well on both desktop and mobile devices.
- Homepage includes the navigation bar and footer sections.

## **Tasks**

- [x] Design the homepage layout with a focus on user engagement, pleasant modern aesthetics and cohesive brand representation.
- [x] Have a full bleed hero image to catch viewers attention on entering the website.
- [x] Implement sections for latest articles, sign up, and key blog information.
- [x] Integrate sign up call to action into the homepage design.
- [x] Include Navigation bar at the top of the homepage.
- [x] Include the Footer section at the bottom of the homepage.
- [x] The homepage layout should be fully responsive for all screen sizes and devices.
