### ISSUE TITLE
User Story - Post Like Interaction

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#10]
EPIC: **User Interaction and Content Engagement**

As a **user** I can **like an article** so that I can show my appreciation for the content.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Users can easily like a post with a single click.
- The total number of likes is displayed on each post.
- The like feature is intuitive and seamlessly integrated into the article layout.

## **Tasks**

- [ ] Develop a 'like' button for each post.
- [ ] Create a field on the post model to store the number of likes for the post.
- [ ] Implement the functionality for incrementing the like field on the post model when button is clicked.
- [ ] Display the number of likes on the post article.
