### ISSUE TITLE
User Story - About Information

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#14]
EPIC: **Website Information**

As a **user** I can **read an informative About page** so that I can **understand the blog's purpose and the people behind it**.

T-Shirt Size: **S**

## **Acceptance Criteria**

- The About page provides clear and concise information about the blog and the reason for its creation.
- The page is easily accessible from the main navigation.
- The content on the About page is engaging and well-presented.
- The about page is responsive so that it is readable from any screen size and device. 

## **Tasks**

- [x] Create content for the About page.
- [x] Design the layout of the About page.
- [x] Integrate menu item for the About page into the blog's main navigation.
- [x] Ensure that the About page layout is responsive and adaptive to all screen sizes and devices.
