### ISSUE TITLE
User Story - Account Sign-Up

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#17]
EPIC: **User Accounts and Authentication**

As a **user**, I can **sign up and create an account with minimal effort**, so that **I can create a profile that will allow me to interact with the blog more easily and publish my own articles**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- The sign-up process is quick and straightforward.
- Signup form correctly validates user input before it is sent.
- The signup form is responsive for smaller screen sizes, ensuring it is easy to fill out.

## **Tasks**

- [x] Design a sign-up form.
- [x] Allow optional email inclusion on the form.
- [x] Ensure that simple and common passwords are not accepted.
- [x] Have input for username.
- [x] Have input for first name.
- [x] Have input for last name.
- [x] Have input for optional email.
- [x] Have input for password.
- [x] Ensure form is responsive for smaller screen sizes.
