### ISSUE TITLE
User Story - Profile Image Uploads

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#19]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **upload my own profile image** so that **I can have a more personalized and visually appealing presence within the platform, fostering a stronger sense of identity and connection with others**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Users can upload a profile photo on account creation
- The profile form supports uploading various image formats.
- A default placeholder image is used when no image is supplied.

## **Tasks**

- [x] Integrate a Cloudinary image upload widget into the profile form.
- [x] Store the images on a the Cloudinary file server.
- [x] Configure Django to serve images from the Cloudinary file server.
- [x] Fetch default placeholder images from the static folder if images are not supplied in the forms.
