### ISSUE TITLE
User Story - Account Login

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#21]
EPIC: **User Accounts and Authentication**

As a **user**, I can **login  when I have created an account**, so that **I can write my own article and also comment on other users articles**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Users can login using their username and password.
- The login process is quick and straightforward.
- Login form correctly validates user input before it is sent.
- The login form is responsive for smaller screen sizes, ensuring it is easy to fill out.

## **Tasks**

- [x] Design a login form.
- [x] Have input for username.
- [x] Have input for password.
- [x] Implement social media authentication.
- [x] Ensure form is responsive for smaller screen sizes.
