### ISSUE TITLE
User Story - Account Logout

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#22]
EPIC: **User Accounts and Authentication**

As a **user**, I can **logout from my account**, so that **I can protect my account from others accessing it and allow other potential users to login**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Users can login using an easy to locate button from the navbar from anywhere in the site.
- The user is asked to confirm before they log out from the site.
- When logged out the user is redirected back to the home page.

## **Tasks**

- [x] Design a logout form.
- [x] Have a logout button in the navbar.
- [x] Have a logout confirmation message appear before the user signs out.
- [x] Have a logout button on the logout confirmation page.
- [x] Redirect user back to the home page on successfully logging out from the site.
