### ISSUE TITLE
User Story - Create Articles

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#23]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **write my own article when I sign up for an account**, so that **I can contribute and share my own knowledge and ideas with the tech community on the site**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- When users are logged in they have access to a page where they can write and submit their own articles.
- Users can choose a title.
- Users can upload a banner hero image for the article.
- Users can choose from a category in which the article belongs to.
- Users can use a WYSIWYG editor on the page to visually format the content of their article.
- The article will be time stamped from the date and time from which it was published.

## **Tasks**

- [x] Design an article form.
- [x] Have input for title.
- [x] Have input for category.
- [x] Have input for article banner image.
- [x] Have WYSIWYG editor for formatting article content.
- [x] Ensure form is responsive for smaller screen sizes.
