### ISSUE TITLE
User Story - CTA Section

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#24]
EPIC: **User Interaction and Content Engagement**

As a **site owner**, I can **have a section to entice readers to sign up**, so that **I can encourage others in the tech industry to contribute to the blog with their own articles**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- There is an area featured on the homepage enticing users to signup for an account.
- A button is present taking the user to the signup page.
- The text heading is clear in its purpose and catchy in its messaging.
- Section is responsive and remains easy to read and interact with on smaller screens.
- Content is positioned nest to eye catching imagery that reinforces the sites design.

## **Tasks**

- [x] Design a CTA section
- [x] Have a section for and image and for the text content.
- [x] If the user is not logged in or does not have an account then add a button taking the user to the signup page.
- [x] If the user is logged in then change the CTA message since they already have an account.
- [x] If the user is logged in then have the button take them to the write article page.
- [x] Ensure that the section is responsive and remains easy to read on smaller screens.
