### ISSUE TITLE
User Story - Notifications

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#25]
EPIC: **User Experience and Interface Design**

As a **user**, I will **receive notifications upon the completion of important tasks**, so that **I receive confirmation feedback that an action has been successfully executed**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- A popup notification is shown when the user signs up.
-  A popup notification is shown when the user logs in.
- A popup notification is shown when the user logs out.

- A popup notification is shown when the user creates and article.
- A popup notification is shown when the user updates and article.
- A popup notification is shown when the user deletes and article.

- A popup notification is shown when the user creates a comment.
- A popup notification is shown when the user updates a comment.
- A popup notification is shown when the user deletes a comment.

## **Tasks**

- [x] Pass Django messages into the correct views.
- [x] Add an 'if' check to the base template to check for messages.
- [x] Create the containing html for the popup component .
- [x] Style and add css animations to the popup component.
- [x] User Javascript to remove the toast popup component after some number of seconds.
