### ISSUE TITLE
User Story - Category Menu

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#26]
EPIC: **Search and Discovery**

As a **user**, I can **filter articles by category**, so that **I can easily find and read articles that are on tech topics I am most interested in**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- There is an interactive menu component that when clicked will filter out the article according to category
- There are five categories to choose from ( Front-end, Back-end, UI/UX Design, Devops and Thoughts and Perspectives).
- The menu component should be response and still usable on smaller screens.
- The category menu should be featured on both the home page and also at the top of the article section.
- Categories are thoughtfully color-coded, providing users with a visually intuitive grouping system.

## **Tasks**

- [x] Design a Category menu component.
- [x] Create the component as an include file so it can be reused in multiple templates.
- [x] Have the category appear over each menu item on hover.
- [x] Have the category color change on the menu bar to reflect the category.
- [x] When clicked it should return the  filtered posts matching the chosen category.
- [x] The menu component itself should be responsive for smaller screens.
