### ISSUE TITLE
User Story - Article Image Uploads

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#27]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **upload my own article banner image** so that **I can make my post stand out and be more visually appealing amongst the other in the site and increase engagement with my content**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- Users can upload a profile photo on article creation
- The profile form supports uploading various image formats.
- A default placeholder image is used when no image is supplied.

## **Tasks**

- [x] Integrate a Cloudinary image upload widget into the article form.
- [x] Store the images on a the Cloudinary file server.
- [x] Configure Django to serve images from the Cloudinary file server.
- [x] Fetch default placeholder images from the static folder if images are not supplied in the forms.
