### ISSUE TITLE
 User Story - Profile Section

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#28]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **have a section showcasing my own personal profile**, so that **I can share information about myself with others in the tech community**.

T-Shirt Size: **XL**

## **Acceptance Criteria**

- There is a separate section of the site for the users profile.
- The user's profile image is displayed prominently at the top.
- Users can share where in the world they live and profession within the tech industry.
- Users can write a short bio about themselves to give more information to other visitors.
- Users can share links to their social media information.
- The profile page should be responsive for smaller screens.

## **Tasks**

- [x] Create a model in the blog app for the profile information.
- [x] Use a django signal to create a profile instance when a new user is saved.
- [x] Design a template for the Profile section.
- [x] Show the user's profile image, name and profession at the top of the page
- [x] Show the users date of birth, optional email and short bio.
- [x] Show the users website links to their social media accounts.
- [x] If the user is logged in then have the button take them to the write article page.
- [x] Ensure that the section is responsive and remains easy to read on smaller screens.
