### ISSUE TITLE
User Story - Update Articles

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#29]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **update any articles I have written** so that **I change them if i wish to fix, correct or add something to the article's content**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- If the user is logged in they will see an edit icon next to the article card and article detail page.
- When the user clicks the icon they will be taken to the article edit form.
- The article form will be populated with the content of the existing blog post.
- When users submit the article they will be notified of the update with a popup notification.
- The article will be updated in the database and correctly display the updated content to the user.

## **Tasks**

- [x] Design the edit icon button.
- [x] Ensure icon appears when user is logged in.
- [x] Ensure icon only appears next to article written by the logged in user or for the site admin.
- [x] Clicking the icon directs the user to the article edit form.
- [x] The article form will be populated with the content of the existing blog post.
- [x] The article form will validate the user input before submission.
- [x] The user will be notified of any invalid fields.
- [x] Popup notification will be displayed when the form is successfully submitted
- [x] Form is responsive for smaller screen sizes.
