### ISSUE TITLE
User Story - Article Cards

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#3]
EPIC: ** Search and Discovery**

As a **user**, I can **view articles as clickable cards with images and summaries** so that **I can decide if I'm interested in reading them**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- Each article is represented by a card with an image and summary.
- Cards are clickable, leading to the full article.
- The design of the cards is visually appealing and consistent with the blog's theme.
- The article card uses an excerpt from the article body text as a preview to the user.

## **Tasks**

- [x] Design the article card layout.
- [x] Implement functionality to query the model to retrieve the corresponding article content.
- [x] Ensure that cards are responsive and align with the overall design.
- [x] Display the article cards hero image at the top.
- [x] Display a text excerpt from the article below the image
- [x] Make article card clickable to direct user the the full article page.
- [x] Assign coloring coding to the article card dynamically depending on the category.
