### ISSUE TITLE
 User Story - Delete Articles

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#30]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **delete any articles I have written** so that **I remove them If i no longer want others to see them**.

T-Shirt Size: **S**

## **Acceptance Criteria**

- If the user is logged in they will see a delete icon next to the article card and article detail page.
- When the user clicks the delete icon they will be taken to a delete confirmation page.
- The user will be given a warning message to confirm the deletion
- When the user clicks the delete button on the confirmation page the article will be successfully removed from the database.
- The article will no longer be visible on the site after deletion.
- A popup notification will be displayed to the user on successful deletion.

## **Tasks**

- [x] Design the edit delete button.
- [x] Use an if conditional on the article card to ensure the delete button appears when user or admin is logged in.
- [x] Use an if conditional in the post detail template to ensure the delete button appears when user or admin is logged in.
- [x] Clicking the icon directs the user to the article delete confirmation page.
- [x] Remove the chosen article from the database when the user clicks the delete button on the confirmation page.
- [x] Pass django message through the view so that a notification will be displayed to the user on successful deletion.
