### ISSUE TITLE
 User Story - Delete Comments

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#31]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **delete any comments I have written** so that **I remove them If i no longer want others to see them**.

T-Shirt Size: **S**

## **Acceptance Criteria**

- If the user is logged in they will see a delete icon next to any comment they have made on an article.
- When the user clicks the delete icon they will be taken to a delete confirmation page.
- The user will be given a warning message to confirm the deletion
- When the user clicks the delete button on the confirmation page the comment will be successfully removed from the database.
- The comment will no longer be visible below the article after deletion.
- A popup notification will be displayed to the user on successful deletion.

## **Tasks**

- [x] Design the delete button.
- [x] Ensure button appears when user is logged in.
- [x] Ensure button only appears next to comment written by the logged in user or for the site admin.
- [x] Direct the user to the comment delete confirmation page when delete button is clicked.
- [x] Removefrom the chosen comment from the database when clicking the delete button on the confirmation page.
- [x] Notify the user with a popup on successful deletion.
