### ISSUE TITLE
User Story - Update Comments

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#32]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **update any comments I have written** so that **I can change them at some point in the future.**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- If the user is logged in they will see a edit button next to any comment they have made on an article.
- When the user clicks the edit icon they will be taken to the comment edit form.
- The comment edit form will be prepopulated with the content of the current comment.
- When the user submits the updated comment it will update the database
- The user will be notified of the successful update via a popup notification.
- The user is redirected back to the post to which the comment belongs.

## **Tasks**

- [x] Design the update button.
- [x] Ensure edit button only appears next to comment written by the logged in user or for the site admin.
- [x] Define the URL path for the article update page.
- [x] Create the view function for comment update.
- [x] Direct the user to the comment update form when delete button is clicked.
- [x] Populate the comment form with the existing content.
- [x] Using django messages on the view, notify the user with a popup on successful update of the comment.
- [x] Redirect the user back to the article the comment belongs to.
