### ISSUE TITLE
User Story - Create Comments

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#33]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **leave comments on articles* so that **I can engage with the community and provide feedback *.

T-Shirt Size: **M**

## **Acceptance Criteria**

- A comment box is available under each article when the user is signed in.
- A sign in link is displayed if the user is not logged in.
- When The user has entered their comment it is added to the database and linked to the current article.
- The user is redirected back the the current article page.
- The user will be notified of the successful comment creation via a popup notification.

## **Tasks**

- [x] Create the model for the comment in the blog database.
- [x] Create the view for creating the comment.
- [x] Pass the comment form into the post detail template.
- [x] Have the view listen for a post request and populate the database with the comment content.
- [x] Redirect the user back to the current article page.
- [x] Using django messages on the view, notify the user with a popup on successful publication of the comment.
