### ISSUE TITLE
User Story - Article Detail Page

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#4]
EPIC: **User Experience and Interface Design**

As a user, I can **access a full-page article section that provides the complete article content** so that **I can properly read and digest all of the article the information in a clean and readable layout**.

T-Shirt Size: **XL**

## **Acceptance Criteria**

- The article detail page displays the full text of the article, along with a hero image and profile image of the author.
- The article detail page displays the title and date at which the article was posted.
- The article detail page shows a comment section below the article when the user is signed into their account.
- The article detail page is fully responsive to ensure an optimal reading experience on any device screen size.
- The article detail page has a comment section below it for users to express opinions and thoughts on the article.

## **Tasks**

- [x] Design the layout for the article detail page, focusing on readability and engagement.
- [x] Implement the backend functionality to retrieve and display full article content and multimedia.
- [x] Ensure that the banner image appears full bleed at the top of the article.
- [x] Show the profile picture of the author.
- [x] Show author name and published date below the article title.
- [x] Show the comment section of below the article when user is logged in.
- [x] Ensure the page is responsive and test on multiple devices.
