### ISSUE TITLE
User Story - Article Comment Section

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#7]
EPIC: **User Interaction and Content Engagement**

As a **user**, I can **leave comments on articles** so that **I can engage with the community and provide feedback**.

T-Shirt Size: **L**

## **Acceptance Criteria**

- A comment section is available under each article if the user is logged in.
- User must be logged in to comment. Have a link to the sign in page if the user is not logged in.
- Display the number of comments on the blog article.
- Have the edit and delete button show next to the comment associated with the logged in user or admin.
- The username and date posted is shown with each comment.

## **Tasks**

- [x] Implement a comment model for the blog app.
- [x] Use an if conditional in the template to show the comment form is the user is logged otherwise have a sign in prompt.
- [x] Create a user form for inputting and posting comments on the post detail template.
- [x] Show the username associated with the comment and the date it was posted.
- [x] Allow users to edit their comments. 
- [x] Allow users to delete their comments.
