### ISSUE TITLE
User Story - Article Category Feature

### ISSUE THREAD

**Issue by ShaneDoyleDev** [ShaneDoyleDev/commit#9]
EPIC: **Search and Discovery**

As a **User**, I have the capability to **select the category for the articles I have created**. So that I can **assign specific categories to them, simplifying the process of locating them through filtering**.

T-Shirt Size: **M**

## **Acceptance Criteria**

- The user interface provides an option for users to select the appropriate category for the article they have written.
- Categories can be selected from a predefined list of five set options.
- Categories are color coded so they are easier to group visually.
- Articles are color coded to reflect the category they belong to.

## **Tasks**

- [x] Add a category field of predefined options to the post model.
- [x] Integrate a selection input into the user interface for article creation, enabling users to designate the appropriate category.
- [x] Create a custom tag in Django to  dynamically color code the articles by matching category.
